password was not updated using chpasswd.sh script
fix for user-mgt.xml not found by addig the conf directory as a config and paxlogin

error: Error updating credentials for user admin : org.wso2.carbon.user.core.UserStoreException: Error while reading realm configuration from file

added config when executing the script to get the user-mgt.xml file which is needed for the RealmConfigXMLProcessor.java to generate the salt value.

issue: https://github.com/wso2/api-manager/issues/1624